-- 建立 numbers 資料表
CREATE TABLE IF NOT EXISTS public.numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 說明：若要啟用 Realtime，請在 Supabase Dashboard 執行：
-- 1. 進入 Database -> Replication
-- 2. 在 'supabase_realtime' 中加入 'numbers' 表
-- 或者執行以下 SQL (僅限部分權限)：
-- alter publication supabase_realtime add table numbers;

-- RLS 建議：
-- 為了讓前端能直接訂閱，需確保 RLS 允許匿名讀取，或根據需求設定 Policy。
-- 範例：允許所有人讀取與新增 (開發測試用)
ALTER TABLE public.numbers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON public.numbers FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.numbers FOR INSERT WITH CHECK (true);
